name: Deploy ADK Agent to Cloud Run

on:
  push:
    branches:
      - feature/tesfa-agentss

jobs:
  deploy:
    name: Deploy ADK Agent
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
      SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ADK (and CLI tools)
        run: |
          pip install google-adk

      - name: Build and smoke-test Docker image
        run: |
          # Build image locally on the runner and run quick tests
          docker build -t tesfa-agent:ci .
          docker run --rm tesfa-agent:ci python -c "import torch; print('CI: torch', torch.__version__)"
          docker run --rm -e GOOGLE_API_KEY='dummy' tesfa-agent:ci python -c "import importlib; importlib.import_module('tesfa_agent'); print('CI: import OK')"

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Tag & push image to GCR
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/tesfa-agent:${{ github.sha }}
          docker tag tesfa-agent:ci $IMAGE
          docker push $IMAGE
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run using pushed image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/tesfa-agent:${{ github.sha }}
          gcloud run deploy tesfa-agent \
            --image="$IMAGE" \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=europe-west1 \
            --platform=managed \
            --memory=4Gi \
            --concurrency=1 \
            --allow-unauthenticated \
            --set-env-vars=GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}",SUPABASE_HOST="${{ secrets.SUPABASE_HOST }}",SUPABASE_DB="${{ secrets.SUPABASE_DB }}",SUPABASE_USER="${{ secrets.SUPABASE_USER }}",SUPABASE_PASSWORD="${{ secrets.SUPABASE_PASSWORD }}",SUPABASE_PORT="${{ secrets.SUPABASE_PORT }}"
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Ensure unauthenticated access is allowed (redundant-safe)
        run: |
          gcloud run services add-iam-policy-binding tesfa-agent \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=europe-west1 \
            --member=allUsers \
            --role=roles/run.invoker