name: Deploy ADK Agent to Cloud Run

on:
  push:
    branches:
      - feature/tesfa-agentss

jobs:
  deploy:
    name: Deploy ADK Agent
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
      SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ADK
        run: pip install google-adk

      - name: Deploy to Cloud Run using ADK (app_name must match Python package)
        run: |
          adk deploy cloud_run \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --service_name=tesfa-agent \
            --app_name=tesfa_agent \
            --region=europe-west1 \
            ./tesfa_agent

      - name: Set runtime environment variables on Cloud Run (secure)
        run: |
          # Use gcloud to set environment variables for the deployed service from GitHub secrets.
          # This ensures the running container sees these as real environment variables.
          gcloud run services update tesfa-agent \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=europe-west1 \
            --update-env-vars=GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}",SUPABASE_HOST="${{ secrets.SUPABASE_HOST }}",SUPABASE_DB="${{ secrets.SUPABASE_DB }}",SUPABASE_USER="${{ secrets.SUPABASE_USER }}",SUPABASE_PASSWORD="${{ secrets.SUPABASE_PASSWORD }}",SUPABASE_PORT="${{ secrets.SUPABASE_PORT }}"

      - name: Ensure unauthenticated access is allowed
        run: |
          gcloud run services add-iam-policy-binding tesfa-agent \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=europe-west1 \
            --member=allUsers \
            --role=roles/run.invoker